import NavBar from '@/components/layout/navbar/NavBar'
import './globals.css'
import { Public_Sans } from 'next/font/google'

const inter = Public_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><NavBar/>{children}</body>
    </html>
  )
}
